development:
  adapter: mysql
  database: rlingclone
  username: root
  password: 


test: &test
  adapter: mysql
  database: rlingclone_test
  username: root
  password: 


production:
  adapter: mysql
  database: rling
  username: root
  password: 

cucumber:
  <<: *test
