development:
  adapter: mysql
  database: rlingclone
  username: root
  password: 


test: &test
  adapter: mysql
  database: rlingclone_test
  username: root
  password: 

staging:
  adapter: mysql2
  database: kangarating
  username: root
  password: 



production:
  adapter: mysql
  database: rlingclone
  username: root
  password: 

cucumber:
  <<: *test
