development:
  adapter: mysql2
  database: rling_dev
  username: root
  password: 
  host: localhost
  pool: 10
  timeout: 5000

test: &test
  adapter: mysql2
  database: rling_test
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: rling_prod
  username: root
  password: 
  host: localhost
  pool: 10
  timeout: 5000

cucumber:
  <<: *test
